% Author:   Seonyeong Park (sp33@illinois.edu)
% Date:     May 3, 2022
%

% Load label
load('label.mat');

% Normal hemoglobin mass concentration ranges of mice
mc_hb = 150; % [g/L]

% Molecular weight of mammalian hemoglobin
mw_hb = 64500; % [g/mol]

% Hemoglobin concentration of blood
c_thb_b = mc_hb/mw_hb; % [mol/L, M]

% Oxygen saturation
s = zeros(size(label, 1), 1);
s(~strcmp(label(:, 1), '')) = 0.95;

% Volume fraction of blood
f_b = zeros(size(label, 1), 1);
f_b(strcmp(label(:, 1), 'body')) = 0.0337;
f_b(strcmp(label(:, 1), 'skin')) = 0.0337;
f_b(strcmp(label(:, 1), 'thyroid')) = 0.044;
f_b(strcmp(label(:, 1), 'lesn')) = 0;
f_b(strcmp(label(:, 1), 'hrt_myoLV')) = 0.044;
f_b(strcmp(label(:, 1), 'hrt_myoRV')) = 0.044;
f_b(strcmp(label(:, 1), 'hrt_myoLA')) = 0.044;
f_b(strcmp(label(:, 1), 'hrt_myoRA')) = 0.044;
f_b(strcmp(label(:, 1), 'bladder')) = 0.044;
f_b(strcmp(label(:, 1), 'vas_def')) = 0.044;
f_b(strcmp(label(:, 1), 'testicular')) = 0.044;
f_b(strcmp(label(:, 1), 'st_wall')) = 0.044;
f_b(strcmp(label(:, 1), 'st_cnts')) = 0.044;
f_b(strcmp(label(:, 1), 'sm_intest')) = 0.044;
f_b(strcmp(label(:, 1), 'large_intest')) = 0.044;
f_b(strcmp(label(:, 1), 'li_air')) = 0.0028;
f_b(strcmp(label(:, 1), 'si_air')) = 0.0028;
f_b(strcmp(label(:, 1), 'hrt_bldplLV')) = 1;
f_b(strcmp(label(:, 1), 'hrt_bldplRV')) = 1;
f_b(strcmp(label(:, 1), 'hrt_bldplLA')) = 1;
f_b(strcmp(label(:, 1), 'hrt_bldplRA')) = 1;
f_b(strcmp(label(:, 1), 'lung')) = 0.133;
f_b(strcmp(label(:, 1), 'airway')) = 0.133;
f_b(strcmp(label(:, 1), 'liver')) = 0.154;
f_b(strcmp(label(:, 1), 'gall_bladder')) = 0.154;
f_b(strcmp(label(:, 1), 'pancreas')) = 0.154;
f_b(strcmp(label(:, 1), 'spleen')) = 0.154;
f_b(strcmp(label(:, 1), 'kidney')) = 0.119;
f_b(strcmp(label(:, 1), 'brain')) = 0.033;
f_b(strcmp(label(:, 1), 'cerebral_cortex')) = 0.033;
f_b(strcmp(label(:, 1), 'cerebellum')) = 0.033;
f_b(strcmp(label(:, 1), 'corpus_callosum')) = 0.033;
f_b(strcmp(label(:, 1), 'brainstem')) = 0.033;
f_b(strcmp(label(:, 1), 'striatum')) = 0.033;
f_b(strcmp(label(:, 1), 'thal')) = 0.033;
f_b(strcmp(label(:, 1), 'hippo')) = 0.033;
f_b(strcmp(label(:, 1), 'hypothalamus')) = 0.033;
f_b(strcmp(label(:, 1), 'amygdala')) = 0.033;
f_b(strcmp(label(:, 1), 'lateral_septal_nuclei')) = 0.033;
f_b(strcmp(label(:, 1), 'anterior_commissure')) = 0.033;
f_b(strcmp(label(:, 1), 'anterior_pretectal_nucleus')) = 0.033;
f_b(strcmp(label(:, 1), 'periaqueductal_gray')) = 0.033;
f_b(strcmp(label(:, 1), 'aqueduct')) = 0.033;
f_b(strcmp(label(:, 1), 'cerebral_peduncle')) = 0.033;
f_b(strcmp(label(:, 1), 'cochlear_nuclei')) = 0.033;
f_b(strcmp(label(:, 1), 'deep_mesencephalic_nuclei')) = 0.033;
f_b(strcmp(label(:, 1), 'fimbria')) = 0.033;
f_b(strcmp(label(:, 1), 'fornix')) = 0.033;
f_b(strcmp(label(:, 1), 'globus_pallidus')) = 0.033;
f_b(strcmp(label(:, 1), 'inferior_colliculus')) = 0.033;
f_b(strcmp(label(:, 1), 'internal_capsule')) = 0.033;
f_b(strcmp(label(:, 1), 'interpeduncular_nucleus')) = 0.033;
f_b(strcmp(label(:, 1), 'lateral_dorsal_nucleus_of_thalamus_actucleus_of_thalamus')) = 0.033;
f_b(strcmp(label(:, 1), 'lateral_geniculate')) = 0.033;
f_b(strcmp(label(:, 1), 'lateral_lemniscus')) = 0.033;
f_b(strcmp(label(:, 1), 'medial_geniculate')) = 0.033;
f_b(strcmp(label(:, 1), 'nucleus_accumbens')) = 0.033;
f_b(strcmp(label(:, 1), 'olfactory_areas')) = 0.033;
f_b(strcmp(label(:, 1), 'optic_tract')) = 0.033;
f_b(strcmp(label(:, 1), 'pontine_gray')) = 0.033;
f_b(strcmp(label(:, 1), 'spinal_trigeminal_tract')) = 0.033;
f_b(strcmp(label(:, 1), 'substantia_nigra')) = 0.033;
f_b(strcmp(label(:, 1), 'superior_colliculus')) = 0.033;
f_b(strcmp(label(:, 1), 'pineal_gland')) = 0.033;
f_b(strcmp(label(:, 1), 'ventral_thalamic_nuclei')) = 0.033;
f_b(strcmp(label(:, 1), 'ventricular_system')) = 0.033;
f_b(strcmp(label(:, 1), 'rib')) = 0.0247;
f_b(strcmp(label(:, 1), 'skull')) = 0.0247;
f_b(strcmp(label(:, 1), 'humerus')) = 0.0247;
f_b(strcmp(label(:, 1), 'radius')) = 0.0247;
f_b(strcmp(label(:, 1), 'ulna')) = 0.0247;
f_b(strcmp(label(:, 1), 'femur')) = 0.0247;
f_b(strcmp(label(:, 1), 'fibula')) = 0.0247;
f_b(strcmp(label(:, 1), 'tibia')) = 0.0247;
f_b(strcmp(label(:, 1), 'patella')) = 0.0247;
f_b(strcmp(label(:, 1), 'bone')) = 0.0247;
f_b(strcmp(label(:, 1), 'marrow')) = 0.0247;
f_b(strcmp(label(:, 1), 'spine')) = 0.0247;

% Volume fraction of water
f_w = zeros(size(label, 1), 1);
f_w(strcmp(label(:, 1), 'body')) = 0.6;
f_w(strcmp(label(:, 1), 'skin')) = 0.6;
f_w(strcmp(label(:, 1), 'thyroid')) = 0.4;
f_w(strcmp(label(:, 1), 'lesn')) = 0.4;
f_w(strcmp(label(:, 1), 'hrt_myoLV')) = 0.4;
f_w(strcmp(label(:, 1), 'hrt_myoRV')) = 0.4;
f_w(strcmp(label(:, 1), 'hrt_myoLA')) = 0.4;
f_w(strcmp(label(:, 1), 'hrt_myoRA')) = 0.4;
f_w(strcmp(label(:, 1), 'bladder')) = 0.4;
f_w(strcmp(label(:, 1), 'vas_def')) = 0.4;
f_w(strcmp(label(:, 1), 'testicular')) = 0.4;
f_w(strcmp(label(:, 1), 'st_wall')) = 0.4;
f_w(strcmp(label(:, 1), 'st_cnts')) = 0.4;
f_w(strcmp(label(:, 1), 'sm_intest')) = 0.4;
f_w(strcmp(label(:, 1), 'large_intest')) = 0.4;
f_w(strcmp(label(:, 1), 'li_air')) = 0.4;
f_w(strcmp(label(:, 1), 'si_air')) = 0.4;
f_w(strcmp(label(:, 1), 'hrt_bldplLV')) = 0;
f_w(strcmp(label(:, 1), 'hrt_bldplRV')) = 0;
f_w(strcmp(label(:, 1), 'hrt_bldplLA')) = 0;
f_w(strcmp(label(:, 1), 'hrt_bldplRA')) = 0;
f_w(strcmp(label(:, 1), 'lung')) = 0.45;
f_w(strcmp(label(:, 1), 'airway')) = 0.45;
f_w(strcmp(label(:, 1), 'liver')) = 0.6;
f_w(strcmp(label(:, 1), 'gall_bladder')) = 0.6;
f_w(strcmp(label(:, 1), 'pancreas')) = 0.6;
f_w(strcmp(label(:, 1), 'spleen')) = 0.6;
f_w(strcmp(label(:, 1), 'kidney')) = 0.8;
f_w(strcmp(label(:, 1), 'brain')) = 0.55;
f_w(strcmp(label(:, 1), 'cerebral_cortex')) = 0.55;
f_w(strcmp(label(:, 1), 'cerebellum')) = 0.55;
f_w(strcmp(label(:, 1), 'corpus_callosum')) = 0.55;
f_w(strcmp(label(:, 1), 'brainstem')) = 0.55;
f_w(strcmp(label(:, 1), 'striatum')) = 0.55;
f_w(strcmp(label(:, 1), 'thal')) = 0.55;
f_w(strcmp(label(:, 1), 'hippo')) = 0.55;
f_w(strcmp(label(:, 1), 'hypothalamus')) = 0.55;
f_w(strcmp(label(:, 1), 'amygdala')) = 0.55;
f_w(strcmp(label(:, 1), 'lateral_septal_nuclei')) = 0.55;
f_w(strcmp(label(:, 1), 'anterior_commissure')) = 0.55;
f_w(strcmp(label(:, 1), 'anterior_pretectal_nucleus')) = 0.55;
f_w(strcmp(label(:, 1), 'periaqueductal_gray')) = 0.55;
f_w(strcmp(label(:, 1), 'aqueduct')) = 0.55;
f_w(strcmp(label(:, 1), 'cerebral_peduncle')) = 0.55;
f_w(strcmp(label(:, 1), 'cochlear_nuclei')) = 0.55;
f_w(strcmp(label(:, 1), 'deep_mesencephalic_nuclei')) = 0.55;
f_w(strcmp(label(:, 1), 'fimbria')) = 0.55;
f_w(strcmp(label(:, 1), 'fornix')) = 0.55;
f_w(strcmp(label(:, 1), 'globus_pallidus')) = 0.55;
f_w(strcmp(label(:, 1), 'inferior_colliculus')) = 0.55;
f_w(strcmp(label(:, 1), 'internal_capsule')) = 0.55;
f_w(strcmp(label(:, 1), 'interpeduncular_nucleus')) = 0.55;
f_w(strcmp(label(:, 1), 'lateral_dorsal_nucleus_of_thalamus_actucleus_of_thalamus')) = 0.55;
f_w(strcmp(label(:, 1), 'lateral_geniculate')) = 0.55;
f_w(strcmp(label(:, 1), 'lateral_lemniscus')) = 0.55;
f_w(strcmp(label(:, 1), 'medial_geniculate')) = 0.55;
f_w(strcmp(label(:, 1), 'nucleus_accumbens')) = 0.55;
f_w(strcmp(label(:, 1), 'olfactory_areas')) = 0.55;
f_w(strcmp(label(:, 1), 'optic_tract')) = 0.55;
f_w(strcmp(label(:, 1), 'pontine_gray')) = 0.55;
f_w(strcmp(label(:, 1), 'spinal_trigeminal_tract')) = 0.55;
f_w(strcmp(label(:, 1), 'substantia_nigra')) = 0.55;
f_w(strcmp(label(:, 1), 'superior_colliculus')) = 0.55;
f_w(strcmp(label(:, 1), 'pineal_gland')) = 0.55;
f_w(strcmp(label(:, 1), 'ventral_thalamic_nuclei')) = 0.55;
f_w(strcmp(label(:, 1), 'ventricular_system')) = 0.55;
f_w(strcmp(label(:, 1), 'rib')) = 0.3;
f_w(strcmp(label(:, 1), 'skull')) = 0.3;
f_w(strcmp(label(:, 1), 'humerus')) = 0.3;
f_w(strcmp(label(:, 1), 'radius')) = 0.3;
f_w(strcmp(label(:, 1), 'ulna')) = 0.3;
f_w(strcmp(label(:, 1), 'femur')) = 0.3;
f_w(strcmp(label(:, 1), 'fibula')) = 0.3;
f_w(strcmp(label(:, 1), 'tibia')) = 0.3;
f_w(strcmp(label(:, 1), 'patella')) = 0.3;
f_w(strcmp(label(:, 1), 'bone')) = 0.3;
f_w(strcmp(label(:, 1), 'marrow')) = 0.3;
f_w(strcmp(label(:, 1), 'spine')) = 0.3;

% Save functional properties
save('func_prop.mat', 'c_thb_b', 's', 'f_b', 'f_w');
